### PR TITLE
Fix request intercept bug

### PR DESCRIPTION
**Pull request by oneroyalace**
This PR resolves a bug in which Selenium would throw errors at Zorki when Zorki ended its Selenium session while still issuing `continue` commands to browser requests. Since we don't care whether or not those laggy requests go through, I've monkeypatched Selenium to not raise exceptions when `continue` commands fail. 

This patch should have a fairly low blast radius. We're only silencing exceptions that come from `continueRequest` commands, and if one of the `continue` commands we care about legitimately fails, Zorki will notice. We could lower the risks of this patch going awry by freezing our Selenium version, but I don't _think_ that'll be necessary. The line we're messing with [hasn't](https://github.com/SeleniumHQ/selenium/blame/c7be1be9e1053488d13aab76a76598dbf0a39a56/rb/lib/selenium/webdriver/devtools.rb#L49) been touched for 3 years. 

# Testing
1. `rake test` (the monkeypatch should be loaded and applied by `zorki.rb`)

### CODE REVIEW

**Comment by oneroyalace** [comment]
Here's some more background on how I chose the monkeypatch solution: https://gist.github.com/oneroyalace/81eb01a1b4cb2cb92cf426f631825c4f

**Comment by cguess** [comment]
OK, weirdly enough the screenshot coming out is blank (attached). I"m looking into this 
d982fb55-94e4-4a17-8239-8b8987152ecd_screenshots

**Comment by cguess** [comment]
So this looks like an issue with Chrome. Not sure why, probably because the page hasn't loaded yet. This is why we use Firefox for YouTube and Twitter screenshotting but I'm not sure what the solution is here. The problem being: we'd have to log in twice. I'm going to look into just using Firefox.

**Comment by cguess** [comment]
OK, figured out what's going on. The page was not loading because, in instagram, we stop the page loading after we have the GraphQL. We do  that on line 78 of `scraper.rb`:
```
page.driver.browser.devtools.callbacks["Fetch.requestPaused"] = []
```

Originally this was to handle the problem that @oneroyalace has solved elsewhere in this PR. This continues to pass tests so far though, so I think this monkey patch did even more good (Though this was a BITCH to figure out).

**Comment by cguess** [comment]
OK! This works in Hypatia's tests on `45-screenshot-pages` as well. If you want me to review finally let me know @oneroyalace

**Pull request merged**
